### PR TITLE
Resolve path by fileId correctly

### LINKED ISSUE #98: OC 9 - files_antivirus stable 9
Hey guys, next to the integrity check the logs also show this error:

```Error while running background job (class: OC\BackgroundJob\Legacy\RegularJob, arguments: Array ( [0] => OCA\Files_Antivirus\Cron\Task [1] => run ) ): {"Exception":"OCP\\Files\\NotFoundException","Message":"File with id \"4\" has not been found.","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_antivirus\/lib\/backgroundscanner.php(78): OC\\Files\\View->getPath(4)\n#1 \/var\/www\/owncloud\/apps\/files_antivirus\/lib\/cron\/task.php(21): OCA\\Files_Antivirus\\BackgroundScanner->run()\n#2 [internal function]: OCA\\Files_Antivirus\\Cron\\Task::run()\n#3 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/legacy\/regularjob.php(28): call_user_func(Array)\n#4 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/job.php(52): OC\\BackgroundJob\\Legacy\\RegularJob->run(Array)\n#5 \/var\/www\/owncloud\/cron.php(141): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#6 {main}","File":"\/var\/www\/owncloud\/lib\/private\/files\/view.php","Line":1639}```

Ubuntu 14.04
OC 9.0.0
PHP 7.0
Apache 2.4.7
MySql 5.6

Anyone?

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes
#98 
https://github.com/owncloud/files_antivirus/issues/109
https://github.com/owncloud/core/issues/25759

### CODE REVIEW

File: lib/backgroundscanner.php [hunk 1]
```diff
@@ -84,21 +100,27 @@ public function run(){
...
 			return;
 		}
 
-
-		$view = new \OC\Files\View('');
 		try {
 			while ($row = $result->fetch()) {
-				$path = $view->getPath($row['fileid']);
+				$fileId = $row['fileid'];
+				$owner = $this->getOwner($fileId);
```
Comment (PVince81) [inline lib/backgroundscanner.php]: Are you excluding federated shares here ? Just asking because today I noticed that it would get a non-resolvable owner (the federated id of the remote user).

File: lib/backgroundscanner.php [hunk 2]
```diff
@@ -110,22 +132,42 @@ public function run(){
...
 	 */
-	protected function initFS(){
-		//Need any valid user to mount FS
-		$results = $this->userManager->search('', 2, 0);
-		$anyUser = array_pop($results);
-		if (is_null($anyUser)) {
-			\OC::$server->getLogger()->error("Failed to setup file system", ['app' => 'files_antivirus']);
-			return false;
+	protected function getUserFolder(IUser $user) {
+		if (!isset($this->userFolders[$user->getUID()])) {
```
Comment (PVince81) [inline lib/backgroundscanner.php]: so these aren't cached in core already ?

**Comment by PVince81** [comment]
What's left to do ?

I saw your bullet list here https://github.com/owncloud/files_antivirus/issues/109#issuecomment-230782092. Are these things we had before and need to re-add to this approach/PR ? Or does the PR match the old behavior feature-wise ?

File: lib/backgroundscanner.php (hunk 2 above)
Comment (VicDeo) [inline lib/backgroundscanner.php]: @PVince81 IDK, blindly copied from tag retention

File: lib/backgroundscanner.php (hunk 1 above)
Comment (VicDeo) [inline lib/backgroundscanner.php]: @PVince81 no. According to the query above :
```
 							$qb->expr()->like('ss.id', $qb->expr()->literal('local::%')),
 							$qb->expr()->like('ss.id', $qb->expr()->literal('home::%'))
```

**Comment by VicDeo** [comment]
@PVince81 Are these things we had before and need to re-add to this approach/PR ? Or does the PR match the old behavior feature-wise ?
The latter (match the old behavior)

**Comment by VicDeo** [comment]
Right now it produces the following:
```
PHP Fatal error:  Call to a member function getStorage() on a non-object in lib/private/Files/View.php on line 1688
PHP Stack trace:
PHP   1. {main}() cron.php:0
PHP   2. OC\BackgroundJob\TimedJob->execute() cron.php:122
PHP   3. OC\BackgroundJob\Job->execute() lib/private/BackgroundJob/TimedJob.php:53
PHP   4. OCA\Files_Antivirus\Cron\Task->run() lib/private/BackgroundJob/Job.php:52
PHP   5. OCA\Files_Antivirus\BackgroundScanner->run() apps/files_antivirus/lib/cron/task.php:32
PHP   6. OC\Files\View->getPath() apps/files_antivirus/lib/backgroundscanner.php:121
```

**Comment by ms270169** [comment]
In _OC\Files\View.getPath()_:
line _$mounts = $manager->findIn($this->fakeRoot);_ is finding the needed mount
line _$mounts[] = $manager->find($this->fakeRoot);_ adds null to the array

After _array_reverse()_ the null is on first position. In the following foreach loop every array element is accessed, also the null. This leads to the fatal error.

Without this error (I prevent acess to null with an is_null(...)), it works.
Please don't forget some additional improvements on antivirus scan (see Conclusion in [issue #25759](https://github.com/owncloud/core/issues/25759#issuecomment-239664445) and [issue #125](https://github.com/owncloud/files_antivirus/issues/125))

File: lib/backgroundscanner.php (hunk 1 above)
Comment (PVince81) [inline lib/backgroundscanner.php]: ouch, this will not work with md5-style storage ids

**Comment by PVince81** [comment]
@VicDeo I think the first goal is to achieve the same functionality like before first in this PR. After merging we can look into improving more stuff.

**Comment by VicDeo** [comment]
@ms270169 thanks for debugging :beer: 
please retest, it should work now

**Comment by VicDeo** [comment]
@PVince81 @DeepDiver1975 ready for review

File: lib/backgroundscanner.php [hunk 3]
```diff
@@ -110,22 +131,43 @@ public function run(){
...
+	/**
+	 * @param IUser $user
+	 */
+	protected function initFilesystemForUser(IUser $user) {
+		if ($this->currentFilesystemUser !== $user->getUID()) {
+			if ($this->currentFilesystemUser !== '') {
+				Filesystem::tearDown();
+			}
+			Filesystem::init($user->getUID(), '/' . $user->getUID() . '/files');
+			$this->userSession->setUser($user);
```
Comment (PVince81) [inline lib/backgroundscanner.php]: at you setting this back to null at some point ? Because multiple bkg jobs could run in a single pass so we don't want a stray user when running the next job...

**Comment by PVince81** [comment]
@ms270169 did you get a chance to test this ? (I don't have the env setup to test it myself)

**Comment by ms270169** [comment]
I have tested last commit c42ebb7b3c20ae9ba3a80d3e57d10a85d381957d.
Works as desired. All files were scanned succuessful.

Be aware, that there is some weakness in implementation.
For example, if a file cannot be found in file-system, scanning breaks down completly because _new Item_ will cause an exception, which breaks the loop.

**Comment by PVince81** [comment]
> For example, if a file cannot be found in file-system, scanning breaks down completly because new Item will cause an exception, which breaks the loop.

@VicDeo Any chance to catch this and continue the loop ?

**Comment by ms270169** [comment]
My recommendation: remove size limit in sql query and add inner try/catch with counter.
For example: 
```
try {
			$cnt = 0;
			while (($row = $result->fetch()) && $cnt++ < self::BATCH_SIZE) {
				$fileId = $row['fileid'];
				try {
					$owner = $this->getOwner($fileId);
					if (!$owner){
						continue;
					}
					$this->initFilesystemForUser($owner);
					$view = \OC\Files\Filesystem::getView();
					$path = $view->getPath($fileId);
					if (!is_null($path)) {
						$item = new Item($this->l10n, $view, $path, $fileId);
						$scanner = $this->scannerFactory->getScanner();
						$status = $scanner->scan($item);
						$status->dispatch($item, true);
					}
				} catch (\Exception $e){
					\OC::$server->getLogger()->warning( __METHOD__ . ', cannot scan fileid ' . $fileId . ', exception: ' . $e->getMessage(), ['app' => 'files_antivirus']);
				}
			}
		} catch (\Exception $e){
			\OC::$server->getLogger()->error( __METHOD__ . ', exception: ' . $e->getMessage(), ['app' => 'files_antivirus']);
		}
```
In case of missing file you will get two entries in log (error _File does not exist_ and warning _cannot scan file_). But every turn 10 files are scanned until all files are scanned.

**Comment by VicDeo** [comment]
@ms270169 I disagree with 'remove size limit in sql query'. It filters  zero-sized files  that are definitely not infected and are known to produce errors as per https://github.com/owncloud/files_antivirus/issues/69

**Comment by VicDeo** [comment]
@ms270169 
I got it. This totally makes sense.

@PVince81 try-catch moved into the loop, user-session reset to null and to prevent looping through unresolvable entries only successfully scanned filed are counted in the batch now

**Comment by dercorn** [comment]
@RealRancor could this be backported to 9.0?

File: lib/backgroundscanner.php [hunk 4]
```diff
@@ -84,48 +99,84 @@ public function run(){
...
-		$view = new \OC\Files\View('');
-		try {
-			while ($row = $result->fetch()) {
-				$path = $view->getPath($row['fileid']);
+		$cnt = 0;
+		while ($row = $result->fetch() && $cnt < self::BATCH_SIZE) {
+			try {
+				$fileId = $row['fileid'];
+				$owner = $this->getOwner($fileId);
+				if (!$owner){
```
Comment (PVince81) [inline lib/backgroundscanner.php]: this might be true if `$owner` is equal to the string 0 ?

**Comment by PVince81** [comment]
@VicDeo code looks good, I haven't tested this. :+1: 

If @ms270169 confirms that it still works then we can count it as a second thumbs up and merge.

**Comment by PVince81** [comment]
@VicDeo how risky would be a backport to stable9 ?

**Comment by VicDeo** [comment]
@PVince81 IMO backport is possible.

**Comment by VicDeo** [comment]
Stable9.1:  https://github.com/owncloud/files_antivirus/issues/127
Stable9: https://github.com/owncloud/files_antivirus/issues/128

**Comment by RealRancor** [comment]
Should also fix https://github.com/owncloud/files_antivirus/issues/98 or am i wrong?

@dercorn I have no idea if stuff can be backported :smile:

**Comment by VicDeo** [comment]
@RealRancor Looks like this

**Comment by ms270169** [comment]
Take attention to brackets!!
In [backgroundscanner.php line 110] (https://github.com/owncloud/files_antivirus/blob/89d4e7b17d1ed3dbad2279d43d4cb873f81bfaad/lib/backgroundscanner.php#L110):
`_while ($row = $result->fetch() && $cnt < self::BATCH_SIZE) {_`
.. row gets a boolean value instead of one row from query result.
Change it to
`_while (($row = $result->fetch()) && $cnt < self::BATCH_SIZE) {_`

**Comment by VicDeo** [comment]
@ms270169 ouch... Thanks for spotting it!

**Comment by VicDeo** [comment]
Stable9: https://github.com/owncloud/files_antivirus/pull/128
Stable9.1: https://github.com/owncloud/files_antivirus/pull/127

**Comment by PVince81** [comment]
@ms270169 mind retesting ?

**Comment by ms270169** [comment]
Everything works as desired.

I have tested cff2a478e4d71b037b8b1fe72f0a7849ce41912a with a setup where one file was deleted manually from file-system, but stays inside oc_filecache. So system is in an abnormal inconsistent state.
All valid files are scanned successfully. Two Exceptions are logged as error (level 3), caused by the missing file:

1. _"message":"File does not exist. File: 155 Path: ..."_
2. _"message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception:"_

Second exception my lead to confusion, it is thrown in [backgroundscanner.php#L130](https://github.com/owncloud/files_antivirus/blob/6bcff02985f1721d6ddd582d28edb2392a616c49/lib/backgroundscanner.php#L130) but _ex.getMessage()_ is empty. Adding some additional message text (like _"scanning file ... fails"_ would be helpful.

**Comment by PVince81** [comment]
@VicDeo can you fix the message separately ?

Merging now so this can finally get into the release

**Comment by PVince81** [comment]
@VicDeo does it need a backport to 8.2 ?
