### PR TITLE
Hide config details about background scan if disabled

### LINKED ISSUE #531: [QA] UI details about background scan should be hidden, when background scan is disabled
Seen with files_antivirus 1.2.1-rc.1 (probably not a regression)

* enable files_antivirus app
* visit admin general settings
* switch background scan from 'Enabled' to 'Disabled'
* The choice what to do with background scan results is still visible. BAD
grafik

Expected behaviour:
* as everything else in the antrivirus UI changes nicely according to context, this setting should do the same.

### PR DESCRIPTION
**Pull request by prsnbrg**
Fix #531

### CODE REVIEW

**Comment by phil-davis** [comment]
- enable files_antivirus app
- visit admin security settings
- switch background scan from 'Enabled' to 'Disabled'

works in real-time.

But when I browse away from the page and come back to it, the details about background scan are displayed:

Screenshot 2023-05-16 at 11-37-39 Settings - ownCloud

There is still something needed to initialize the correct show/hide when the page is first rendered.

**Comment by prsnbrg** [comment]
@phil-davis please review. I fixed the missing status of show/hide on initalization

**Review by phil-davis — COMMENTED** [review]
WFM - devs please review.

File: js/settings.js [hunk 1]
```diff
@@ -171,6 +171,17 @@ function av_mode_show_options(str){
 	$('#av_host, #av_port, #av_request_service, #av_response_header').attr('disabled', false);
 	$('p.av_host, p.av_port, p.av_mode_icap').show('slow');
 }
+
+function infected_action_show_options(str){
+	if (str === 'true') {
+		$('p.infected_action').show('slow');
+		$('#av_infected_action').attr('disabled', false);
```
Comment (jvillafanez) [inline js/settings.js:178]: Disabling might not be the best option. The option will be shown or hidden along with the `p.infected_action`, so I don't think we need to do anything.
This will leave us with fewer lines of code, which can be moved inside the callback, no need to create a function for now

**Comment by prsnbrg** [comment]
@phil-davis @jnweiger Please review and if possible include this in the current release.

**Review by phil-davis — APPROVED** [review]
WFM - @jvillafanez @DeepDiver1975 or somebody else, please review.

**Review by jvillafanez — APPROVED** [review]
